# Form implementation generated from reading ui file 'projectgui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_voting_menu(object):
    def setupUi(self, voting_menu):
        voting_menu.setObjectName("voting_menu")
        voting_menu.resize(235, 230)
        voting_menu.setMinimumSize(QtCore.QSize(235, 230))
        voting_menu.setMaximumSize(QtCore.QSize(235, 230))
        voting_menu.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(parent=voting_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.vote_menu = QtWidgets.QLabel(parent=self.centralwidget)
        self.vote_menu.setGeometry(QtCore.QRect(70, 0, 121, 21))
        self.vote_menu.setObjectName("vote_menu")
        self.john_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.john_button.setGeometry(QtCore.QRect(90, 90, 51, 16))
        self.john_button.setObjectName("john_button")
        self.jane_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jane_button.setGeometry(QtCore.QRect(90, 70, 51, 16))
        self.jane_button.setObjectName("jane_button")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.id_label.setObjectName("id_label")
        self.id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(90, 20, 51, 16))
        self.id_input.setObjectName("id_input")
        self.candidtes_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidtes_label.setGeometry(QtCore.QRect(80, 50, 71, 16))
        self.candidtes_label.setObjectName("candidtes_label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 110, 91, 17))
        self.pushButton.setObjectName("pushButton")
        voting_menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=voting_menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 235, 18))
        self.menubar.setObjectName("menubar")
        voting_menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=voting_menu)
        self.statusbar.setObjectName("statusbar")
        voting_menu.setStatusBar(self.statusbar)

        self.retranslateUi(voting_menu)
        QtCore.QMetaObject.connectSlotsByName(voting_menu)

    def retranslateUi(self, voting_menu):
        _translate = QtCore.QCoreApplication.translate
        voting_menu.setWindowTitle(_translate("voting_menu", "MainWindow"))
        self.vote_menu.setText(_translate("voting_menu", "VOTING APPLICATION"))
        self.john_button.setText(_translate("voting_menu", "John"))
        self.jane_button.setText(_translate("voting_menu", "Jane"))
        self.id_label.setText(_translate("voting_menu", "ID:"))
        self.candidtes_label.setText(_translate("voting_menu", "CANDIDATES"))
        self.pushButton.setText(_translate("voting_menu", "SUBMIT VOTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    voting_menu = QtWidgets.QMainWindow()
    ui = Ui_voting_menu()
    ui.setupUi(voting_menu)
    voting_menu.show()
    sys.exit(app.exec())
